<script lang="ts">
  import SQLiteRenderer from 'statue-ssg/components/SQLiteRenderer.svelte';
import ComponentInfo from 'statue-ssg/components/ComponentInfo.svelte';

  // Query to get all components, ordered by template and name
  const query = `
    SELECT
      name,
      template,
      path,
      description,
      last_modified,
      size,
      last_commit,
      is_modified
    FROM components
    ORDER BY
      CASE WHEN template IS NULL THEN 0 ELSE 1 END,
      template,
      name
  `;
</script>

<svelte:head>
  <title>Statue Components Registry</title>
  <meta name="description" content="Browse all Svelte components available in Statue SSG and its templates" />
</svelte:head>

<div class="components-page">
  <header>
    <nav class="breadcrumb">
      <a href="/">← Back to Demos</a>
    </nav>
    <h1>Component Registry</h1>
    <p class="subtitle">
      All Svelte components in Statue SSG, automatically discovered and documented.
      This page demonstrates SQLite dynamic components querying a database generated from the codebase.
    </p>
  </header>

  <SQLiteRenderer
    databases={[{ name: 'components', path: '/components.db' }]}
    query={query}
    component={ComponentInfo}
    propMapping={{
      name: 'name',
      template: 'template',
      path: 'path',
      description: 'description',
      last_modified: 'last_modified',
      size: 'size',
      last_commit: 'last_commit',
      is_modified: 'is_modified'
    }}
    containerProps={{ columns: 2, gap: '24px' }}
    emptyMessage="No components found. Run 'npm run generate:components-db' to create the database."
  />

  <footer class="page-footer">
    <p>
      💡 <strong>How it works:</strong> The <code>components.db</code> database is generated by scanning
      all <code>.svelte</code> files in the project and templates. Each component's metadata
      (name, path, git status, etc.) is stored in the database and displayed using
      <code>SQLiteRenderer</code> with the <code>ComponentInfo</code> component.
    </p>
    <p>
      To regenerate the database, run: <code>npm run generate:components-db</code>
    </p>
  </footer>
</div>

<style>
  .components-page {
    max-width: 1400px;
    margin: 0 auto;
    padding: 40px 20px;
  }

  header {
    text-align: center;
    margin-bottom: 60px;
  }

  .breadcrumb {
    margin-bottom: 24px;
  }

  .breadcrumb a {
    display: inline-block;
    color: var(--color-muted);
    text-decoration: none;
    font-size: 14px;
    font-weight: 500;
    transition: color 0.2s ease;
  }

  .breadcrumb a:hover {
    color: var(--color-primary);
  }

  h1 {
    font-size: 48px;
    font-weight: 700;
    color: var(--color-primary);
    margin: 0 0 16px 0;
    letter-spacing: -0.02em;
  }

  .subtitle {
    font-size: 18px;
    color: var(--color-muted);
    margin: 0;
    max-width: 800px;
    margin: 0 auto;
    line-height: 1.6;
  }

  .page-footer {
    margin-top: 80px;
    padding: 32px;
    background-color: color-mix(in srgb, var(--color-card) 50%, transparent);
    border: 1px solid var(--color-border);
    border-radius: 12px;
  }

  .page-footer p {
    color: var(--color-muted);
    font-size: 14px;
    line-height: 1.8;
    margin: 0 0 12px 0;
  }

  .page-footer p:last-child {
    margin-bottom: 0;
  }

  .page-footer code {
    background-color: color-mix(in srgb, var(--color-text) 10%, transparent);
    padding: 3px 8px;
    border-radius: 4px;
    font-size: 13px;
    font-family: 'Monaco', 'Menlo', 'Consolas', monospace;
    color: var(--color-primary);
  }

  @media (max-width: 768px) {
    h1 {
      font-size: 36px;
    }

    .subtitle {
      font-size: 16px;
    }

    .page-footer {
      margin-top: 60px;
      padding: 24px;
    }
  }
</style>
