#!/usr/bin/env node

import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.resolve(__dirname, '../src/lib/components');
const indexFile = path.resolve(__dirname, '../src/lib/index.ts');

/**
 * Recursively find all .svelte files in a directory
 */
async function findSvelteFiles(dir) {
	const files = [];
	const entries = await fs.readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			// Recursively search subdirectories
			const subFiles = await findSvelteFiles(fullPath);
			files.push(...subFiles);
		} else if (entry.isFile() && entry.name.endsWith('.svelte')) {
			files.push(fullPath);
		}
	}

	return files;
}

/**
 * Extract component name and relative path from full path
 */
function getComponentInfo(fullPath, componentsDir) {
	const relativePath = path.relative(componentsDir, fullPath);
	const componentName = path.basename(fullPath, '.svelte');
	return { relativePath, componentName };
}

async function generateExports() {
	try {
		// Recursively find all .svelte files
		const svelteFiles = await findSvelteFiles(componentsDir);

		if (svelteFiles.length === 0) {
			console.warn('No Svelte components found in', componentsDir);
			return;
		}

		// Sort for consistent output
		svelteFiles.sort();

		// Group components by directory for better organization
		const componentsByDir = {};

		for (const file of svelteFiles) {
			const { relativePath, componentName } = getComponentInfo(file, componentsDir);
			const dir = path.dirname(relativePath);

			// Normalize path separators for consistent exports
			const importPath = `./components/${relativePath}`.replace(/\\/g, '/');

			if (!componentsByDir[dir]) {
				componentsByDir[dir] = [];
			}
			componentsByDir[dir].push({ componentName, importPath });
		}

		// Generate export statements sorted by component name
		const exports = [];

		// First, add all root-level components
		if (componentsByDir['.']) {
			componentsByDir['.'].sort((a, b) => a.componentName.localeCompare(b.componentName));
			exports.push(...componentsByDir['.'].map((c) => `export { default as ${c.componentName} } from '${c.importPath}';`));
		}

		// Then subdirectories (remove '.' from keys first)
		const subdirs = Object.keys(componentsByDir).filter((d) => d !== '.').sort();
		for (const dir of subdirs) {
			const dirLabel = dir.replace(/\//g, ' - ');
			exports.push(`\n// ${dirLabel}`);
			componentsByDir[dir].sort((a, b) => a.componentName.localeCompare(b.componentName));
			exports.push(...componentsByDir[dir].map((c) => `export { default as ${c.componentName} } from '${c.importPath}';`));
		}

		// Generate new content with generated file warning
		const newContent =
			'// place files you want to import through the `$lib` alias in this folder.\n' +
			'//\n' +
			'// *** AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ***\n' +
			'// This file is automatically generated by: npm run generate:exports\n' +
			'// To add new components, simply place them in src/lib/components/\n' +
			'//\n\n' +
			'// Export all components for easy importing\n' +
			exports.join('\n') +
			'\n';

		// Write to index.ts
		await fs.writeFile(indexFile, newContent, 'utf-8');

		console.log(`✓ Generated exports for ${svelteFiles.length} components`);
	} catch (error) {
		console.error('Error generating exports:', error.message);
		process.exit(1);
	}
}

generateExports();

